using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HRIS.Api.Migrations;

public partial class BatchC_ApprovalSimple : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(name:"REF_Letter_Type", columns:table=>new { letter_type_id=table.Column<int>(type:"INTEGER",nullable:false).Annotation("Sqlite:Autoincrement",true), name=table.Column<string>(type:"TEXT",maxLength:150,nullable:false), template_document_id=table.Column<int>(type:"INTEGER",nullable:true), is_active=table.Column<bool>(type:"INTEGER",nullable:false) }, constraints:table=>{table.PrimaryKey("PK_REF_Letter_Type",x=>x.letter_type_id);table.ForeignKey("FK_REF_Letter_Type_TRX_Document_template_document_id",x=>x.template_document_id,"TRX_Document","document_id",onDelete:ReferentialAction.Restrict);});
        migrationBuilder.CreateTable(name:"REF_Vehicle_Type", columns:table=>new { vehicle_type_id=table.Column<int>(type:"INTEGER",nullable:false).Annotation("Sqlite:Autoincrement",true), name=table.Column<string>(type:"TEXT",maxLength:100,nullable:false) }, constraints:table=>table.PrimaryKey("PK_REF_Vehicle_Type",x=>x.vehicle_type_id));
        migrationBuilder.CreateTable(name:"REF_Module_Eligibility", columns:table=>new { eligibility_id=table.Column<int>(type:"INTEGER",nullable:false).Annotation("Sqlite:Autoincrement",true), employment_type_id=table.Column<int>(type:"INTEGER",nullable:false), module_code=table.Column<string>(type:"TEXT",maxLength:30,nullable:false), is_allowed=table.Column<bool>(type:"INTEGER",nullable:false) }, constraints:table=>{table.PrimaryKey("PK_REF_Module_Eligibility",x=>x.eligibility_id);table.ForeignKey("FK_REF_Module_Eligibility_REF_Employment_Type_employment_type_id",x=>x.employment_type_id,"REF_Employment_Type","employment_type_id",onDelete:ReferentialAction.Restrict);});
        migrationBuilder.CreateTable(name:"TRX_Declaration_Template", columns:table=>new { template_id=table.Column<int>(type:"INTEGER",nullable:false).Annotation("Sqlite:Autoincrement",true), title=table.Column<string>(type:"TEXT",maxLength:200,nullable:false), content=table.Column<string>(type:"TEXT",nullable:false), is_active=table.Column<bool>(type:"INTEGER",nullable:false), created_at=table.Column<DateTime>(type:"TEXT",nullable:false), created_by=table.Column<int>(type:"INTEGER",nullable:true), updated_at=table.Column<DateTime>(type:"TEXT",nullable:true), updated_by=table.Column<int>(type:"INTEGER",nullable:true) }, constraints:table=>table.PrimaryKey("PK_TRX_Declaration_Template",x=>x.template_id));
        migrationBuilder.CreateTable(name:"TRX_Family_Change_Request", columns:table=>new { change_id=table.Column<int>(type:"INTEGER",nullable:false).Annotation("Sqlite:Autoincrement",true), employee_id=table.Column<int>(type:"INTEGER",nullable:false), family_id=table.Column<int>(type:"INTEGER",nullable:true), action=table.Column<string>(type:"TEXT",maxLength:20,nullable:false), family_name=table.Column<string>(type:"TEXT",maxLength:150,nullable:false), relationship_id=table.Column<int>(type:"INTEGER",nullable:false), gender_id=table.Column<int>(type:"INTEGER",nullable:true), birth_date=table.Column<DateOnly>(type:"TEXT",nullable:true), is_dependent=table.Column<bool>(type:"INTEGER",nullable:false), wedding_date=table.Column<DateOnly>(type:"TEXT",nullable:true), status=table.Column<string>(type:"TEXT",maxLength:20,nullable:false), created_at=table.Column<DateTime>(type:"TEXT",nullable:false), created_by=table.Column<int>(type:"INTEGER",nullable:true), updated_at=table.Column<DateTime>(type:"TEXT",nullable:true), updated_by=table.Column<int>(type:"INTEGER",nullable:true) }, constraints:table=>{table.PrimaryKey("PK_TRX_Family_Change_Request",x=>x.change_id);table.ForeignKey("FK_TRX_Family_Change_Request_MST_Employee_employee_id",x=>x.employee_id,"MST_Employee","employee_id",onDelete:ReferentialAction.Restrict);table.ForeignKey("FK_TRX_Family_Change_Request_MST_Employee_Family_family_id",x=>x.family_id,"MST_Employee_Family","family_id",onDelete:ReferentialAction.Restrict);table.ForeignKey("FK_TRX_Family_Change_Request_REF_Relationship_relationship_id",x=>x.relationship_id,"REF_Relationship","relationship_id",onDelete:ReferentialAction.Restrict);table.ForeignKey("FK_TRX_Family_Change_Request_REF_Gender_gender_id",x=>x.gender_id,"REF_Gender","gender_id",onDelete:ReferentialAction.Restrict);});
        migrationBuilder.CreateTable(name:"TRX_Letter_Request", columns:table=>new { letter_id=table.Column<int>(type:"INTEGER",nullable:false).Annotation("Sqlite:Autoincrement",true), employee_id=table.Column<int>(type:"INTEGER",nullable:false), letter_type_id=table.Column<int>(type:"INTEGER",nullable:false), purpose=table.Column<string>(type:"TEXT",maxLength:500,nullable:false), destination=table.Column<string>(type:"TEXT",maxLength:300,nullable:true), status=table.Column<string>(type:"TEXT",maxLength:20,nullable:false), issued_document_id=table.Column<int>(type:"INTEGER",nullable:true), issued_at=table.Column<DateTime>(type:"TEXT",nullable:true), created_at=table.Column<DateTime>(type:"TEXT",nullable:false), created_by=table.Column<int>(type:"INTEGER",nullable:true), updated_at=table.Column<DateTime>(type:"TEXT",nullable:true), updated_by=table.Column<int>(type:"INTEGER",nullable:true) }, constraints:table=>{table.PrimaryKey("PK_TRX_Letter_Request",x=>x.letter_id);table.ForeignKey("FK_TRX_Letter_Request_MST_Employee_employee_id",x=>x.employee_id,"MST_Employee","employee_id",onDelete:ReferentialAction.Restrict);table.ForeignKey("FK_TRX_Letter_Request_REF_Letter_Type_letter_type_id",x=>x.letter_type_id,"REF_Letter_Type","letter_type_id",onDelete:ReferentialAction.Restrict);table.ForeignKey("FK_TRX_Letter_Request_TRX_Document_issued_document_id",x=>x.issued_document_id,"TRX_Document","document_id",onDelete:ReferentialAction.Restrict);});
        migrationBuilder.CreateTable(name:"TRX_Parking_Registration", columns:table=>new { parking_id=table.Column<int>(type:"INTEGER",nullable:false).Annotation("Sqlite:Autoincrement",true), employee_id=table.Column<int>(type:"INTEGER",nullable:false), vehicle_type_id=table.Column<int>(type:"INTEGER",nullable:false), plate_number=table.Column<string>(type:"TEXT",maxLength:30,nullable:false), status=table.Column<string>(type:"TEXT",maxLength:20,nullable:false), card_ready_at=table.Column<DateTime>(type:"TEXT",nullable:true), card_collected_at=table.Column<DateTime>(type:"TEXT",nullable:true), created_at=table.Column<DateTime>(type:"TEXT",nullable:false), created_by=table.Column<int>(type:"INTEGER",nullable:true), updated_at=table.Column<DateTime>(type:"TEXT",nullable:true), updated_by=table.Column<int>(type:"INTEGER",nullable:true) }, constraints:table=>{table.PrimaryKey("PK_TRX_Parking_Registration",x=>x.parking_id);table.ForeignKey("FK_TRX_Parking_Registration_MST_Employee_employee_id",x=>x.employee_id,"MST_Employee","employee_id",onDelete:ReferentialAction.Restrict);table.ForeignKey("FK_TRX_Parking_Registration_REF_Vehicle_Type_vehicle_type_id",x=>x.vehicle_type_id,"REF_Vehicle_Type","vehicle_type_id",onDelete:ReferentialAction.Restrict);});
        migrationBuilder.CreateTable(name:"TRX_Declaration_Submission", columns:table=>new { submission_id=table.Column<int>(type:"INTEGER",nullable:false).Annotation("Sqlite:Autoincrement",true), template_id=table.Column<int>(type:"INTEGER",nullable:false), employee_id=table.Column<int>(type:"INTEGER",nullable:false), agreed_at=table.Column<DateTime>(type:"TEXT",nullable:false), document_id=table.Column<int>(type:"INTEGER",nullable:true), created_at=table.Column<DateTime>(type:"TEXT",nullable:false), created_by=table.Column<int>(type:"INTEGER",nullable:true), updated_at=table.Column<DateTime>(type:"TEXT",nullable:true), updated_by=table.Column<int>(type:"INTEGER",nullable:true) }, constraints:table=>{table.PrimaryKey("PK_TRX_Declaration_Submission",x=>x.submission_id);table.ForeignKey("FK_TRX_Declaration_Submission_TRX_Declaration_Template_template_id",x=>x.template_id,"TRX_Declaration_Template","template_id",onDelete:ReferentialAction.Restrict);table.ForeignKey("FK_TRX_Declaration_Submission_MST_Employee_employee_id",x=>x.employee_id,"MST_Employee","employee_id",onDelete:ReferentialAction.Restrict);table.ForeignKey("FK_TRX_Declaration_Submission_TRX_Document_document_id",x=>x.document_id,"TRX_Document","document_id",onDelete:ReferentialAction.Restrict);});
        migrationBuilder.CreateTable(name:"TRX_Laptop_Request", columns:table=>new { laptop_id=table.Column<int>(type:"INTEGER",nullable:false).Annotation("Sqlite:Autoincrement",true), employee_id=table.Column<int>(type:"INTEGER",nullable:false), asset_tag=table.Column<string>(type:"TEXT",maxLength:50,nullable:true), model=table.Column<string>(type:"TEXT",maxLength:200,nullable:false), price=table.Column<long>(type:"INTEGER",nullable:true), status=table.Column<string>(type:"TEXT",maxLength:30,nullable:false), created_at=table.Column<DateTime>(type:"TEXT",nullable:false), created_by=table.Column<int>(type:"INTEGER",nullable:true), updated_at=table.Column<DateTime>(type:"TEXT",nullable:true), updated_by=table.Column<int>(type:"INTEGER",nullable:true) }, constraints:table=>{table.PrimaryKey("PK_TRX_Laptop_Request",x=>x.laptop_id);table.ForeignKey("FK_TRX_Laptop_Request_MST_Employee_employee_id",x=>x.employee_id,"MST_Employee","employee_id",onDelete:ReferentialAction.Restrict);});
        migrationBuilder.CreateTable(name:"TRX_Service_Award", columns:table=>new { award_id=table.Column<int>(type:"INTEGER",nullable:false).Annotation("Sqlite:Autoincrement",true), employee_id=table.Column<int>(type:"INTEGER",nullable:false), service_years=table.Column<int>(type:"INTEGER",nullable:false), due_date=table.Column<DateOnly>(type:"TEXT",nullable:false), status=table.Column<string>(type:"TEXT",maxLength:20,nullable:false), given_at=table.Column<DateTime>(type:"TEXT",nullable:true), created_at=table.Column<DateTime>(type:"TEXT",nullable:false), created_by=table.Column<int>(type:"INTEGER",nullable:true), updated_at=table.Column<DateTime>(type:"TEXT",nullable:true), updated_by=table.Column<int>(type:"INTEGER",nullable:true) }, constraints:table=>{table.PrimaryKey("PK_TRX_Service_Award",x=>x.award_id);table.ForeignKey("FK_TRX_Service_Award_MST_Employee_employee_id",x=>x.employee_id,"MST_Employee","employee_id",onDelete:ReferentialAction.Restrict);});
        migrationBuilder.CreateTable(name:"TRX_Laptop_Status_Log", columns:table=>new { log_id=table.Column<int>(type:"INTEGER",nullable:false).Annotation("Sqlite:Autoincrement",true), laptop_id=table.Column<int>(type:"INTEGER",nullable:false), status=table.Column<string>(type:"TEXT",maxLength:30,nullable:false), changed_by=table.Column<int>(type:"INTEGER",nullable:false), changed_at=table.Column<DateTime>(type:"TEXT",nullable:false), note=table.Column<string>(type:"TEXT",maxLength:500,nullable:true), created_at=table.Column<DateTime>(type:"TEXT",nullable:false), created_by=table.Column<int>(type:"INTEGER",nullable:true), updated_at=table.Column<DateTime>(type:"TEXT",nullable:true), updated_by=table.Column<int>(type:"INTEGER",nullable:true) }, constraints:table=>{table.PrimaryKey("PK_TRX_Laptop_Status_Log",x=>x.log_id);table.ForeignKey("FK_TRX_Laptop_Status_Log_TRX_Laptop_Request_laptop_id",x=>x.laptop_id,"TRX_Laptop_Request","laptop_id",onDelete:ReferentialAction.Cascade);table.ForeignKey("FK_TRX_Laptop_Status_Log_SYS_User_changed_by",x=>x.changed_by,"SYS_User","user_id",onDelete:ReferentialAction.Restrict);});
        migrationBuilder.CreateIndex(name:"IX_REF_Letter_Type_template_document_id",table:"REF_Letter_Type",column:"template_document_id"); migrationBuilder.CreateIndex(name:"IX_REF_Module_Eligibility_employment_type_id_module_code",table:"REF_Module_Eligibility",columns:new[]{"employment_type_id","module_code"},unique:true);
        migrationBuilder.CreateIndex(name:"IX_TRX_Family_Change_Request_employee_id_status",table:"TRX_Family_Change_Request",columns:new[]{"employee_id","status"});
        migrationBuilder.CreateIndex(name:"IX_TRX_Letter_Request_employee_id",table:"TRX_Letter_Request",column:"employee_id"); migrationBuilder.CreateIndex(name:"IX_TRX_Letter_Request_letter_type_id",table:"TRX_Letter_Request",column:"letter_type_id"); migrationBuilder.CreateIndex(name:"IX_TRX_Letter_Request_issued_document_id",table:"TRX_Letter_Request",column:"issued_document_id");
        migrationBuilder.CreateIndex(name:"IX_TRX_Parking_Registration_employee_id",table:"TRX_Parking_Registration",column:"employee_id"); migrationBuilder.CreateIndex(name:"IX_TRX_Parking_Registration_vehicle_type_id",table:"TRX_Parking_Registration",column:"vehicle_type_id"); migrationBuilder.CreateIndex(name:"IX_TRX_Parking_Registration_plate_number",table:"TRX_Parking_Registration",column:"plate_number",unique:true);
        migrationBuilder.CreateIndex(name:"IX_TRX_Declaration_Submission_template_id",table:"TRX_Declaration_Submission",column:"template_id"); migrationBuilder.CreateIndex(name:"IX_TRX_Declaration_Submission_employee_id",table:"TRX_Declaration_Submission",column:"employee_id"); migrationBuilder.CreateIndex(name:"IX_TRX_Declaration_Submission_document_id",table:"TRX_Declaration_Submission",column:"document_id");
        migrationBuilder.CreateIndex(name:"IX_TRX_Laptop_Request_employee_id",table:"TRX_Laptop_Request",column:"employee_id"); migrationBuilder.CreateIndex(name:"IX_TRX_Laptop_Status_Log_laptop_id",table:"TRX_Laptop_Status_Log",column:"laptop_id"); migrationBuilder.CreateIndex(name:"IX_TRX_Laptop_Status_Log_changed_by",table:"TRX_Laptop_Status_Log",column:"changed_by");
        migrationBuilder.CreateIndex(name:"IX_TRX_Service_Award_employee_id_service_years",table:"TRX_Service_Award",columns:new[]{"employee_id","service_years"},unique:true);
    }
    protected override void Down(MigrationBuilder migrationBuilder){migrationBuilder.DropTable(name:"TRX_Laptop_Status_Log");migrationBuilder.DropTable(name:"REF_Module_Eligibility");migrationBuilder.DropTable(name:"TRX_Service_Award");migrationBuilder.DropTable(name:"TRX_Laptop_Request");migrationBuilder.DropTable(name:"TRX_Declaration_Submission");migrationBuilder.DropTable(name:"TRX_Parking_Registration");migrationBuilder.DropTable(name:"TRX_Letter_Request");migrationBuilder.DropTable(name:"TRX_Family_Change_Request");migrationBuilder.DropTable(name:"TRX_Declaration_Template");migrationBuilder.DropTable(name:"REF_Vehicle_Type");migrationBuilder.DropTable(name:"REF_Letter_Type");}
}
